Repository the-metalworks/cosmere-rpg, pull requests merged in 2025-08, with the labels that each got.

#516 fix: adversary type dialog styling
  src/style/dialog.scss
  src/style/module.scss
  src/system/applications/actor/dialogs/edit-creature-type.ts
  src/system/utils/templates.ts
  src/templates/actors/adversary/dialogs/edit-creature-type.hbs
Labels: type | bug, involves | ui

#529 Fix(styling): Add Styling to Several Select Options Menus
  src/style/dialog.scss
  src/style/sheets/actor/adversary.scss
Labels: involves | ui, involves | document sheets

#545 chore(localization): general localization update to reduce hardcoding
  src/lang/en.json
  src/style/chat/module.scss
  src/system/applications/actor/components/actions-list.ts
  src/templates/actors/character/components/paths.hbs
  src/templates/actors/components/attributes.hbs
  src/templates/chat/roll-damage.hbs
  src/templates/item/components/event-rules-list.hbs
Labels: involves | localization
