Repository the-metalworks/cosmere-rpg, pull requests merged in 2025-03, with the labels that each got.

#280 fix: correctly evaluate currency quantity
  src/system/applications/actor/base.ts
  src/system/applications/actor/components/equipment-list.ts
  src/system/data/actor/common.ts
Labels: bug

#281 fix: collapsible field behaviours
  src/system/applications/actor/base.ts
  src/system/applications/item/base.ts
Labels: bug

#283 fix: html field event propogation
  src/system/applications/actor/base.ts
  src/system/applications/item/base.ts
Labels: bug

#284 feat: style cosmere default theme
  src/assets/art/banner_actor_cosmere_bot_dark.webp
  src/assets/art/banner_actor_cosmere_bot_light.webp
  src/assets/art/banner_actor_cosmere_top_dark.webp
  src/assets/art/banner_actor_cosmere_top_light.webp
  src/assets/art/texture_sheet_cosmere_dark.webp
  src/assets/art/texture_sheet_cosmere_light.webp
  src/assets/art/texture_sheet_default_dark.webp
  src/assets/art/texture_sheet_default_light.webp
  src/lang/en.json
  src/style.scss
  src/style/sheets/actor/module.scss
Labels: ui, ux, character sheet

#290 feat: roll config styling and damage dice advantage mechanics
  src/lang/en.json
  src/style/chat/module.scss
  src/style/dialog.scss
  src/style/module.scss
  src/style/sheets/item/module.scss
  src/system/applications/actor/dialogs/short-rest.ts
  src/system/applications/dialogs/attack-configuration.ts
  src/system/applications/dialogs/pick-dice-result.ts
  src/system/applications/dialogs/roll-configuration.ts
  src/system/applications/item/dialogs/item-consume.ts
  src/system/dice/d20-roll.ts
  src/system/dice/damage-roll.ts
  src/system/dice/index.ts
  src/system/dice/plot-die.ts
  src/system/documents/actor.ts
  src/system/documents/chat-message.ts
  src/system/documents/item.ts
  src/system/utils/generic.ts
  src/system/utils/templates.ts
  src/templates/item/dialog/item-consume.hbs
  src/templates/roll/dialogs/attack-config.hbs
  src/templates/roll/dialogs/d20-config.hbs
  src/templates/roll/dialogs/pick-dice-result.hbs
  src/templates/roll/dialogs/roll-configuration.hbs
Labels: dice calculation

#286 feat(hooks): implement basic hooks
  src/system/dice/d20-roll.ts
  src/system/dice/damage-roll.ts
  src/system/dice/index.ts
  src/system/documents/actor.ts
  src/system/documents/chat-message.ts
  src/system/documents/item.ts
  src/system/types/cosmere.ts
  src/system/types/hooks.ts
  src/system/utils/migration/index.ts
Labels: ux, feature request, homebrewing

#303 fix: currency fallback icon
  src/style/sheets/actor/module.scss
  src/system/applications/actor/components/currency-list.ts
  src/system/types/config.ts
  src/templates/actors/components/currency-list.hbs
Labels: bug
