Repository the-metalworks/cosmere-rpg, pull requests merged in 2025-04, with the labels that each got.

#305 Fix incorrect context popup positioning
  src/system/applications/actor/components/character/connections-list.ts
  src/system/applications/actor/components/character/goals-list.ts
  src/system/applications/utils/context-menu.ts
Labels: bug, ui, ux

#323 fix(character sheets): properly display movement rates in config dialog
  src/system/applications/actor/dialogs/configure-movement-rate.ts
  src/templates/actors/dialogs/configure-movement-rate.hbs
Labels: bug, ui, character sheet

#327 Fix(localization): context dependent 'add' button #133
  src/lang/en.json
  src/system/applications/actor/components/actions-list.ts
  src/templates/actors/components/actions-list.hbs
Labels: ui, ux, localization, Enhancement

#343 fix(items): allow power items to roll damage
  src/system/data/item/power.ts
  src/templates/item/power/partials/power-details-tab.hbs
Labels: bug, data models, Enhancement

#326 Feat(ux): skill rank alternative setting method #137
  src/lang/en.json
  src/style/module.scss
  src/system/applications/actor/components/adversary/skills-group.ts
  src/system/applications/actor/components/skill.ts
  src/system/settings.ts
  src/system/utils/handlebars/index.ts
  src/templates/actors/components/skill.hbs
Labels: ui, ux, feature request, character sheet
