Repository the-metalworks/cosmere-rpg, pull requests merged in 2025-06, with the labels that each got.

#393 fix: hide roll mode drop down in roll config
  src/system/applications/dialogs/attack-configuration.ts
  src/system/applications/dialogs/roll-configuration.ts
  src/templates/roll/dialogs/roll-configuration.hbs
Labels: bug

#399 refactor: config register api changes
  src/lang/en.json
  src/system/api/actor.ts
  src/system/api/general.ts
  src/system/api/helper.ts
  src/system/api/index.ts
  src/system/api/item.ts
  src/system/api/sheet.ts
  src/system/api/style.ts
  src/system/applications/actor/components/actions-list.ts
  src/system/constants/hooks.ts
  src/system/hooks/item-event-system/events.ts
  src/system/hooks/item-event-system/handlers/execute-macro.ts
  src/system/hooks/item-event-system/handlers/grant-expertises.ts
  src/system/hooks/item-event-system/handlers/grant-items.ts
  src/system/hooks/item-event-system/handlers/modify-attribute.ts
  src/system/hooks/item-event-system/handlers/modify-skill-rank.ts
  src/system/hooks/item-event-system/handlers/remove-expertises.ts
  src/system/hooks/item-event-system/handlers/remove-items.ts
  src/system/hooks/item-event-system/handlers/set-attribute.ts
  src/system/hooks/item-event-system/handlers/set-skill-rank.ts
  src/system/hooks/item-event-system/handlers/update-actor.ts
  src/system/hooks/item-event-system/handlers/update-item.ts
  src/system/hooks/item-event-system/handlers/use-item.ts
  src/system/types/config.ts
Labels: api

#398 feat(migrations): add manual migration support for world data and compendiums
  src/index.ts
  src/system/hooks/item-event-system/index.ts
  src/system/types/migration.ts
  src/system/utils/data.ts
  src/system/utils/global.ts
  src/system/utils/migration/index.ts
  src/system/utils/migration/migrations/0.2-0.3.ts
  src/system/utils/migration/migrations/0.3-1.0.ts
Labels: ux, feature request, Enhancement, homebrewing

#371 feat(items): support variable resource costs
  src/lang/en.json
  src/style/dialog.scss
  src/system/applications/item/base.ts
  src/system/applications/item/components/details-activation.ts
  src/system/applications/item/dialogs/item-consume.ts
  src/system/data/item/mixins/activatable.ts
  src/system/documents/item.ts
  src/system/types/utils.ts
  src/system/utils/data.ts
  src/system/utils/handlebars/index.ts
  src/system/utils/handlebars/types.ts
  src/system/utils/migration/migrations/0.3-1.0.ts
  src/templates/actors/components/actions-list.hbs
  src/templates/item/components/details-activation.hbs
  src/templates/item/dialog/item-consume.hbs
Labels: ui, ux, feature request, data models

#418 Feat: Register Adversary Actions Action Type
  src/lang/en.json
  src/system/config.ts
  src/system/types/cosmere.ts
Labels: ux, rule/mechanic
